"""File storage abstraction.

Phase 1 writes to a local directory that the API and worker share via a Docker
volume. Phase 6 adds an S3 implementation behind this same interface, which is
why callers only ever handle an opaque `key`.
"""

from __future__ import annotations

import hashlib
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import BinaryIO, Protocol

from core.config import settings

_CHUNK_SIZE = 1024 * 1024


class FileTooLarge(Exception):
    pass


class StorageError(Exception):
    pass


@dataclass(frozen=True)
class StoredFile:
    key: str
    size: int
    #: Content hash. Unused in Phase 1; becomes the idempotency key in Phase 2.
    sha256: str


class Storage(Protocol):
    def save(self, src: BinaryIO, original_name: str) -> StoredFile: ...
    def open(self, key: str) -> BinaryIO: ...
    def delete(self, key: str) -> None: ...


class LocalDiskStorage:
    def __init__(self, root: Path, max_bytes: int) -> None:
        self.root = Path(root)
        self.max_bytes = max_bytes
        self.root.mkdir(parents=True, exist_ok=True)

    def _resolve(self, key: str) -> Path:
        # Keys are generated by save(), but never trust one round-tripped
        # through the database.
        if "/" in key or "\\" in key or key in {"", ".", ".."}:
            raise StorageError(f"Refusing to resolve suspicious storage key: {key!r}")
        return self.root / key

    def save(self, src: BinaryIO, original_name: str) -> StoredFile:
        suffix = Path(original_name).suffix.lower()[:16]
        key = f"{uuid.uuid4().hex}{suffix}"
        dest = self._resolve(key)

        digest = hashlib.sha256()
        size = 0
        try:
            with dest.open("wb") as out:
                while True:
                    chunk = src.read(_CHUNK_SIZE)
                    if not chunk:
                        break
                    size += len(chunk)
                    if size > self.max_bytes:
                        raise FileTooLarge(
                            f"Upload exceeds the {self.max_bytes} byte limit"
                        )
                    digest.update(chunk)
                    out.write(chunk)
        except BaseException:
            dest.unlink(missing_ok=True)
            raise

        return StoredFile(key=key, size=size, sha256=digest.hexdigest())

    def open(self, key: str) -> BinaryIO:
        path = self._resolve(key)
        if not path.is_file():
            raise StorageError(f"Stored file is missing: {key}")
        return path.open("rb")

    def delete(self, key: str) -> None:
        self._resolve(key).unlink(missing_ok=True)


_storage: Storage | None = None


def get_storage() -> Storage:
    global _storage
    if _storage is None:
        _storage = LocalDiskStorage(
            root=settings.UPLOAD_DIR, max_bytes=settings.MAX_UPLOAD_BYTES
        )
    return _storage
