"""File storage.

Phase 1 defined this interface with a single local-disk implementation, on the
bet that Phase 6 would want S3 and the swap should be a one-file change. This
is that file, and it was.

Callers only ever handle an opaque `key`, so nothing outside this module knows
or cares which backend is in use - `jobs.file_path` holds the same key either
way, and no migration was needed to switch.
"""

from __future__ import annotations

import hashlib
import logging
import uuid
from dataclasses import dataclass
from pathlib import Path
from tempfile import SpooledTemporaryFile
from typing import BinaryIO, Protocol

from core.config import settings

logger = logging.getLogger(__name__)

_CHUNK_SIZE = 1024 * 1024
#: Spool to disk past this; below it the buffer stays in memory.
_SPOOL_THRESHOLD = 8 * 1024 * 1024


class FileTooLarge(Exception):
    pass


class StorageError(Exception):
    pass


@dataclass(frozen=True)
class StoredFile:
    key: str
    size: int
    #: Content hash. Becomes the job's idempotency key.
    sha256: str


class Storage(Protocol):
    def save(self, src: BinaryIO, original_name: str) -> StoredFile: ...
    def open(self, key: str) -> BinaryIO: ...
    def delete(self, key: str) -> None: ...


def _new_key(original_name: str) -> str:
    suffix = Path(original_name).suffix.lower()[:16]
    return f"{uuid.uuid4().hex}{suffix}"


def _validate_key(key: str) -> str:
    # Keys are generated by save(), but never trust one round-tripped through
    # the database.
    if "/" in key or "\\" in key or key in {"", ".", ".."}:
        raise StorageError(f"Refusing to resolve suspicious storage key: {key!r}")
    return key


def _buffer_and_hash(src: BinaryIO, max_bytes: int) -> tuple[SpooledTemporaryFile, int, str]:
    """Stream `src` into a spooled buffer, hashing and size-capping as we go.

    Buffering rather than streaming straight to the backend is deliberate: the
    hash has to be known before the upload is committed, and the size cap has
    to be enforced without leaving a half-written object behind. The cap is
    25MB by default, so the buffer is bounded.
    """
    buffer: SpooledTemporaryFile = SpooledTemporaryFile(max_size=_SPOOL_THRESHOLD)
    digest = hashlib.sha256()
    size = 0

    try:
        while True:
            chunk = src.read(_CHUNK_SIZE)
            if not chunk:
                break
            size += len(chunk)
            if size > max_bytes:
                raise FileTooLarge(f"Upload exceeds the {max_bytes} byte limit")
            digest.update(chunk)
            buffer.write(chunk)
    except BaseException:
        buffer.close()
        raise

    buffer.seek(0)
    return buffer, size, digest.hexdigest()


class LocalDiskStorage:
    """Local directory, shared between API and worker by a Docker volume."""

    def __init__(self, root: Path, max_bytes: int) -> None:
        self.root = Path(root)
        self.max_bytes = max_bytes
        self.root.mkdir(parents=True, exist_ok=True)

    def _resolve(self, key: str) -> Path:
        return self.root / _validate_key(key)

    def save(self, src: BinaryIO, original_name: str) -> StoredFile:
        key = _new_key(original_name)
        dest = self._resolve(key)
        buffer, size, sha256 = _buffer_and_hash(src, self.max_bytes)
        try:
            with dest.open("wb") as out:
                while True:
                    chunk = buffer.read(_CHUNK_SIZE)
                    if not chunk:
                        break
                    out.write(chunk)
        except BaseException:
            dest.unlink(missing_ok=True)
            raise
        finally:
            buffer.close()
        return StoredFile(key=key, size=size, sha256=sha256)

    def open(self, key: str) -> BinaryIO:
        path = self._resolve(key)
        if not path.is_file():
            raise StorageError(f"Stored file is missing: {key}")
        return path.open("rb")

    def delete(self, key: str) -> None:
        self._resolve(key).unlink(missing_ok=True)


class S3Storage:
    """S3 (or any S3-compatible endpoint, which is how it is tested locally).

    Credentials come from boto3's standard chain - environment variables in
    development, an instance role in production. Nothing here reads or stores
    an access key.
    """

    def __init__(
        self,
        bucket: str,
        max_bytes: int,
        prefix: str = "",
        endpoint_url: str | None = None,
        region: str | None = None,
    ) -> None:
        import boto3  # imported lazily so the local backend needs no AWS SDK

        self.bucket = bucket
        self.prefix = prefix
        self.max_bytes = max_bytes
        self.client = boto3.client(
            "s3", endpoint_url=endpoint_url, region_name=region
        )

    def _object_key(self, key: str) -> str:
        return f"{self.prefix}{_validate_key(key)}"

    def save(self, src: BinaryIO, original_name: str) -> StoredFile:
        key = _new_key(original_name)
        buffer, size, sha256 = _buffer_and_hash(src, self.max_bytes)
        try:
            self.client.upload_fileobj(buffer, self.bucket, self._object_key(key))
        finally:
            buffer.close()
        return StoredFile(key=key, size=size, sha256=sha256)

    def open(self, key: str) -> BinaryIO:
        """Download into a seekable buffer.

        S3's streaming body is forward-only, and pypdf needs to seek - a PDF's
        cross-reference table lives at the end of the file. Downloading into a
        spooled buffer keeps the interface identical to the local backend.
        """
        from botocore.exceptions import ClientError

        buffer: SpooledTemporaryFile = SpooledTemporaryFile(max_size=_SPOOL_THRESHOLD)
        try:
            self.client.download_fileobj(self.bucket, self._object_key(key), buffer)
        except ClientError as exc:
            buffer.close()
            code = exc.response.get("Error", {}).get("Code")
            if code in {"404", "NoSuchKey"}:
                raise StorageError(f"Stored file is missing: {key}") from exc
            raise
        except BaseException:
            buffer.close()
            raise

        buffer.seek(0)
        return buffer  # type: ignore[return-value]

    def delete(self, key: str) -> None:
        self.client.delete_object(Bucket=self.bucket, Key=self._object_key(key))


_storage: Storage | None = None


def build_storage() -> Storage:
    """Construct the configured backend. Exposed for tests."""
    if settings.STORAGE_BACKEND == "s3":
        logger.info(
            "Using S3 storage: bucket=%s prefix=%r endpoint=%s",
            settings.S3_BUCKET,
            settings.S3_PREFIX,
            settings.S3_ENDPOINT_URL or "aws",
        )
        return S3Storage(
            bucket=settings.S3_BUCKET,
            max_bytes=settings.MAX_UPLOAD_BYTES,
            prefix=settings.S3_PREFIX,
            endpoint_url=settings.S3_ENDPOINT_URL,
            region=settings.AWS_REGION,
        )

    return LocalDiskStorage(
        root=settings.UPLOAD_DIR, max_bytes=settings.MAX_UPLOAD_BYTES
    )


def get_storage() -> Storage:
    global _storage
    if _storage is None:
        _storage = build_storage()
    return _storage


def reset_storage() -> None:
    """Drop the cached backend so a config change takes effect. Tests only."""
    global _storage
    _storage = None
